<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <AssemblyName>GMA</AssemblyName>
    <Product>GMA</Product>
    <ApplicationIcon>GMA.ico</ApplicationIcon>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)'=='Debug'">
    <DefineConstants>DEBUG;TRACE;TRANSPORT_LOG;PLAYBACK_ENGINE_LOG</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)'=='Release'">
    <DefineConstants>TRACE</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NAudio" Version="2.2.1" />
    <PackageReference Include="TagLibSharp" Version="2.3.0" />
    <PackageReference Include="System.Speech" Version="10.0.5" />
    <PackageReference Include="NAudio.Vorbis" Version="*" />
  </ItemGroup>

</Project>